### ISSUE TITLE
Failed to process batch for class 'StateCodes.StateCodes' for job id 

### ISSUE THREAD

**Issue by mattandneil** [mattandneil/statecodes#1]
Batch job, after running for 51 hours 23 minutes spontaneously stopped displaying status:

> "Failed to process batch for class 'StateCodes.StateCodes' for job id '7071t00001GG00j'

![Screen Shot 2019-06-05 at 17 57 38](https://user-images.githubusercontent.com/6777144/58975347-9f6f8c80-87bc-11e9-9d20-c2e038ba148b.png)

**Comment by DMB28th** [comment]
Got it to work!  thanks for all your help!  

I want to note for anyone that comes into an issue while uploading the XML File from a Mac,  use this tool to create the zip file in a PC format.  That way you won't encounter this error - https://medium.com/@wangyidan621/salesforce-workbench-zip-deployment-no-package-xml-found-error-on-mac-ec7ce49a7126

http://www.yellowmug.com/yemuzip/
