### ISSUE TITLE
Choosing different regions/states before load

### ISSUE THREAD

**Issue by Samwize1976** [mattandneil/statecodes#5]
Gents, this looks like a promissing solution for us and our migration of 4000+codes.

I'm unable to instal the package though, seems to fail.
Should this be loaded to production for it to work?

I have very few details on why it fails from the SF email notification.

Additionally, is there a way to modify the code to load the regions/States without the "CountryCode-" value beofre the state?
Ex: Load "CA" instead of "US-CA".

**Comment by mattandneil** [comment]
@Samwize1976 URL updated - working better?

**Comment by mattandneil** [comment]
@Samwize1976 Regarding different codes - target values can be modified prior to starting the batch:

![statecode-json](https://user-images.githubusercontent.com/6777144/118533958-9b866c00-b740-11eb-8e8b-2b8e841a7fac.png)

**Comment by Samwize1976** [comment]
Thanks for the reply guys.

We noticed that after loading everything manually and activating it, that
our org completely failed and got crippled with errors on many objects.

After some digging, we came to realize that SFDC does not like codes to be
identical.  Example CA for California and Capellan Luxembourg.

When attempting to then edit the codes to US-CA and LU-CA, we get errors
that sf will not accept special characters or spaces in the codes.

This then makes me wonder how your code would successfully push ‘LU-CA’ =>
‘Capellen’...or any other code since they all contain the infamous “-“.

:)
Please enlighten me gentlemen,

Thomas

**Comment by Samwize1976** [comment]
I’m very surprised.  Following the load of 4000+ regions, it crashed out
system.

I’m not certain if sf support’s claim is that we have a repeat of country
code or. Repeat of region code.

I’ll have to dig in but at first glance we did not repeat any country code.

**Comment by Samwize1976** [comment]
Running batch now in our Full SB.  Hopefully it fixes our issues.
Will keep you posted.
